language: java
jdk:
- oraclejdk8
sudo: required

script: gradle check executeFeatures -Ptoken=ff45c1d546bba5a12f2ac2bc64c08ef4
branches:
only: develop

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org

